env:
  browser: true
  es2021: true
  node: true
  jest: true
extends:
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
ignorePatterns: [dist/**/*, docs/**/*]
rules:
  indent: ['error', 4]
  comma-dangle: ['error', 'always-multiline']
  curly: ['error', 'multi-or-nest']
  one-var: 'off'
  space-before-function-paren: ['error', {
    'anonymous': 'never',
    'named': 'never',
    'asyncArrow': 'always'
  }]
  no-use-before-define: 'off' # False-positives with TypeScript type definitions
  no-unused-vars: 'off' # False-positives with TypeScript enum
  '@typescript-eslint/no-unused-vars': ['error']
